version: '2'

services:
    web:
        build: .
        volumes:
            - ./config/default.conf:/etc/nginx/conf.d/default.conf
            - /mnt/storage/files:/usr/share/nginx/html
        ports:
            - 8080:8080
        
              
        restart: unless-stopped      

